// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enums.proto

#include "enums.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_enums_2eproto = nullptr;
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_enums_2eproto[84];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_enums_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_enums_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_enums_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\013enums.proto*\360\n\n\027EPublishedFileQueryTyp"
  "e\022)\n%k_PublishedFileQueryType_RankedByVo"
  "te\020\000\0224\n0k_PublishedFileQueryType_RankedB"
  "yPublicationDate\020\001\022B\n>k_PublishedFileQue"
  "ryType_AcceptedForGameRankedByAcceptance"
  "Date\020\002\022*\n&k_PublishedFileQueryType_Ranke"
  "dByTrend\020\003\022F\nBk_PublishedFileQueryType_F"
  "avoritedByFriendsRankedByPublicationDate"
  "\020\004\022D\n@k_PublishedFileQueryType_CreatedBy"
  "FriendsRankedByPublicationDate\020\005\0225\n1k_Pu"
  "blishedFileQueryType_RankedByNumTimesRep"
  "orted\020\006\022J\nFk_PublishedFileQueryType_Crea"
  "tedByFollowedUsersRankedByPublicationDat"
  "e\020\007\022(\n$k_PublishedFileQueryType_NotYetRa"
  "ted\020\010\022=\n9k_PublishedFileQueryType_Ranked"
  "ByTotalUniqueSubscriptions\020\t\0222\n.k_Publis"
  "hedFileQueryType_RankedByTotalVotesAsc\020\n"
  "\022,\n(k_PublishedFileQueryType_RankedByVot"
  "esUp\020\013\022/\n+k_PublishedFileQueryType_Ranke"
  "dByTextSearch\020\014\0222\n.k_PublishedFileQueryT"
  "ype_RankedByPlaytimeTrend\020\r\0222\n.k_Publish"
  "edFileQueryType_RankedByTotalPlaytime\020\016\022"
  "9\n5k_PublishedFileQueryType_RankedByAver"
  "agePlaytimeTrend\020\017\022<\n8k_PublishedFileQue"
  "ryType_RankedByLifetimeAveragePlaytime\020\020"
  "\022:\n6k_PublishedFileQueryType_RankedByPla"
  "ytimeSessionsTrend\020\021\022=\n9k_PublishedFileQ"
  "ueryType_RankedByLifetimePlaytimeSession"
  "s\020\022\022\?\n;k_PublishedFileQueryType_RankedBy"
  "InappropriateContentRating\020\023\0224\n0k_Publis"
  "hedFileQueryType_RankedByBanContentCheck"
  "\020\024\0224\n0k_PublishedFileQueryType_RankedByL"
  "astUpdatedDate\020\025\0223\n/k_PublishedFileQuery"
  "Type_RankedByNumParentItems\020\026\0229\n5k_Publi"
  "shedFileQueryType_RankedByNumParentColle"
  "ctions\020\027*\274\001\n#EPublishedFileInappropriate"
  "Provider\0221\n-k_EPublishedFileInappropriat"
  "eProvider_Invalid\020\000\0220\n,k_EPublishedFileI"
  "nappropriateProvider_Google\020\001\0220\n,k_EPubl"
  "ishedFileInappropriateProvider_Amazon\020\002*"
  "\325\002\n!EPublishedFileInappropriateResult\0222\n"
  ".k_EPublishedFileInappropriateResult_Not"
  "Scanned\020\000\0224\n0k_EPublishedFileInappropria"
  "teResult_VeryUnlikely\020\001\0220\n,k_EPublishedF"
  "ileInappropriateResult_Unlikely\020\036\0220\n,k_E"
  "PublishedFileInappropriateResult_Possibl"
  "e\0202\022.\n*k_EPublishedFileInappropriateResu"
  "lt_Likely\020K\0222\n.k_EPublishedFileInappropr"
  "iateResult_VeryLikely\020d*\261\003\n\021EPersonaStat"
  "eFlag\022\'\n#k_EPersonaStateFlag_HasRichPres"
  "ence\020\001\022&\n\"k_EPersonaStateFlag_InJoinable"
  "Game\020\002\022\036\n\032k_EPersonaStateFlag_Golden\020\004\022*"
  "\n&k_EPersonaStateFlag_RemotePlayTogether"
  "\020\010\022&\n!k_EPersonaStateFlag_ClientTypeWeb\020"
  "\200\002\022)\n$k_EPersonaStateFlag_ClientTypeMobi"
  "le\020\200\004\022*\n%k_EPersonaStateFlag_ClientTypeT"
  "enfoot\020\200\010\022%\n k_EPersonaStateFlag_ClientT"
  "ypeVR\020\200\020\022*\n%k_EPersonaStateFlag_LaunchTy"
  "peGamepad\020\200 \022-\n(k_EPersonaStateFlag_Laun"
  "chTypeCompatTool\020\200@*\260\002\n\025EContentCheckPro"
  "vider\022#\n\037k_EContentCheckProvider_Invalid"
  "\020\000\022-\n)k_EContentCheckProvider_Google_DEP"
  "RECATED\020\001\022\"\n\036k_EContentCheckProvider_Ama"
  "zon\020\002\022!\n\035k_EContentCheckProvider_Local\020\003"
  "\022*\n&k_EContentCheckProvider_GoogleVertex"
  "AI\020\004\022(\n$k_EContentCheckProvider_GoogleGe"
  "mini\020\005\022&\n\"k_EContentCheckProvider_SteamL"
  "earn\020\006*\223\t\n\031EProfileCustomizationType\022&\n\""
  "k_EProfileCustomizationTypeInvalid\020\000\0226\n2"
  "k_EProfileCustomizationTypeRareAchieveme"
  "ntShowcase\020\001\022,\n(k_EProfileCustomizationT"
  "ypeGameCollector\020\002\022+\n\'k_EProfileCustomiz"
  "ationTypeItemShowcase\020\003\022,\n(k_EProfileCus"
  "tomizationTypeTradeShowcase\020\004\022%\n!k_EProf"
  "ileCustomizationTypeBadges\020\005\022+\n\'k_EProfi"
  "leCustomizationTypeFavoriteGame\020\006\0221\n-k_E"
  "ProfileCustomizationTypeScreenshotShowca"
  "se\020\007\022)\n%k_EProfileCustomizationTypeCusto"
  "mText\020\010\022,\n(k_EProfileCustomizationTypeFa"
  "voriteGroup\020\t\022-\n)k_EProfileCustomization"
  "TypeRecommendation\020\n\022+\n\'k_EProfileCustom"
  "izationTypeWorkshopItem\020\013\022)\n%k_EProfileC"
  "ustomizationTypeMyWorkshop\020\014\022.\n*k_EProfi"
  "leCustomizationTypeArtworkShowcase\020\r\022,\n("
  "k_EProfileCustomizationTypeVideoShowcase"
  "\020\016\022%\n!k_EProfileCustomizationTypeGuides\020"
  "\017\022\'\n#k_EProfileCustomizationTypeMyGuides"
  "\020\020\022+\n\'k_EProfileCustomizationTypeAchieve"
  "ments\020\021\022)\n%k_EProfileCustomizationTypeGr"
  "eenlight\020\022\022+\n\'k_EProfileCustomizationTyp"
  "eMyGreenlight\020\023\022%\n!k_EProfileCustomizati"
  "onTypeSalien\020\024\0225\n1k_EProfileCustomizatio"
  "nTypeLoyaltyRewardReactions\020\025\0224\n0k_EProf"
  "ileCustomizationTypeSingleArtworkShowcas"
  "e\020\026\0228\n4k_EProfileCustomizationTypeAchiev"
  "ementsCompletionist\020\027\022%\n!k_EProfileCusto"
  "mizationTypeReplay\020\030*\310\001\n\033EPublishedFileS"
  "torageSystem\022(\n$k_EPublishedFileStorageS"
  "ystemInvalid\020\000\022,\n(k_EPublishedFileStorag"
  "eSystemLegacyCloud\020\001\022&\n\"k_EPublishedFile"
  "StorageSystemDepot\020\002\022)\n%k_EPublishedFile"
  "StorageSystemUGCCloud\020\003*\227\001\n\031ECloudStorag"
  "ePersistState\022(\n$k_ECloudStoragePersistS"
  "tatePersisted\020\000\022(\n$k_ECloudStoragePersis"
  "tStateForgotten\020\001\022&\n\"k_ECloudStoragePers"
  "istStateDeleted\020\002*\350\001\n\022ESDCardFormatStage"
  "\022 \n\034k_ESDCardFormatStage_Invalid\020\000\022!\n\035k_"
  "ESDCardFormatStage_Starting\020\001\022 \n\034k_ESDCa"
  "rdFormatStage_Testing\020\002\022!\n\035k_ESDCardForm"
  "atStage_Rescuing\020\003\022#\n\037k_ESDCardFormatSta"
  "ge_Formatting\020\004\022#\n\037k_ESDCardFormatStage_"
  "Finalizing\020\005*\225\002\n\023EStorageFormatStage\022!\n\035"
  "k_EStorageFormatStage_Invalid\020\000\022$\n k_ESt"
  "orageFormatStage_NotRunning\020\001\022\"\n\036k_EStor"
  "ageFormatStage_Starting\020\002\022!\n\035k_EStorageF"
  "ormatStage_Testing\020\003\022\"\n\036k_EStorageFormat"
  "Stage_Rescuing\020\004\022$\n k_EStorageFormatStag"
  "e_Formatting\020\005\022$\n k_EStorageFormatStage_"
  "Finalizing\020\006*\204\001\n\025ESystemFanControlMode\022\""
  "\n\036k_SystemFanControlMode_Invalid\020\000\022#\n\037k_"
  "SystemFanControlMode_Disabled\020\001\022\"\n\036k_Sys"
  "temFanControlMode_Default\020\002*\213\001\n\023EColorGa"
  "mutLabelSet\022 \n\034k_ColorGamutLabelSet_Defa"
  "ult\020\000\022$\n k_ColorGamutLabelSet_sRGB_Nativ"
  "e\020\001\022,\n(k_ColorGamutLabelSet_Native_sRGB_"
  "Boosted\020\002*}\n\024EWindowStackingOrder\022\"\n\036k_E"
  "WindowStackingOrder_Invalid\020\000\022\036\n\032k_EWind"
  "owStackingOrder_Top\020\001\022!\n\035k_EWindowStacki"
  "ngOrder_Bottom\020\002*\300\003\n\024EBluetoothDeviceTyp"
  "e\022!\n\035k_BluetoothDeviceType_Invalid\020\000\022!\n\035"
  "k_BluetoothDeviceType_Unknown\020\001\022\037\n\033k_Blu"
  "etoothDeviceType_Phone\020\002\022\"\n\036k_BluetoothD"
  "eviceType_Computer\020\003\022!\n\035k_BluetoothDevic"
  "eType_Headset\020\004\022$\n k_BluetoothDeviceType"
  "_Headphones\020\005\022\"\n\036k_BluetoothDeviceType_S"
  "peakers\020\006\022$\n k_BluetoothDeviceType_Other"
  "Audio\020\007\022\037\n\033k_BluetoothDeviceType_Mouse\020\010"
  "\022\"\n\036k_BluetoothDeviceType_Joystick\020\t\022!\n\035"
  "k_BluetoothDeviceType_Gamepad\020\n\022\"\n\036k_Blu"
  "etoothDeviceType_Keyboard\020\013*\302\001\n\025ESpeaker"
  "Configuration\022!\n\035k_ESpeakerConfiguration"
  "_Other\020\000\022\"\n\036k_ESpeakerConfiguration_Ster"
  "eo\020\001\022\036\n\032k_ESpeakerConfiguration_51\020\002\022\036\n\032"
  "k_ESpeakerConfiguration_71\020\003\022\"\n\036k_ESpeak"
  "erConfiguration_51_Ac3\020\004*\200\001\n\025ESystemAudi"
  "oDirection\022\"\n\036k_SystemAudioDirection_Inv"
  "alid\020\000\022 \n\034k_SystemAudioDirection_Input\020\001"
  "\022!\n\035k_SystemAudioDirection_Output\020\002*\361\002\n\023"
  "ESystemAudioChannel\022 \n\034k_SystemAudioChan"
  "nel_Invalid\020\000\022#\n\037k_SystemAudioChannel_Ag"
  "gregated\020\001\022\"\n\036k_SystemAudioChannel_Front"
  "Left\020\002\022#\n\037k_SystemAudioChannel_FrontRigh"
  "t\020\003\022\034\n\030k_SystemAudioChannel_LFE\020\004\022!\n\035k_S"
  "ystemAudioChannel_BackLeft\020\005\022\"\n\036k_System"
  "AudioChannel_BackRight\020\006\022$\n k_SystemAudi"
  "oChannel_FrontCenter\020\007\022 \n\034k_SystemAudioC"
  "hannel_Unknown\020\010\022\035\n\031k_SystemAudioChannel"
  "_Mono\020\t*\311\001\n\024ESystemAudioPortType\022!\n\035k_Sy"
  "stemAudioPortType_Invalid\020\000\022!\n\035k_SystemA"
  "udioPortType_Unknown\020\001\022\"\n\036k_SystemAudioP"
  "ortType_Audio32f\020\002\022 \n\034k_SystemAudioPortT"
  "ype_Midi8b\020\003\022%\n!k_SystemAudioPortType_Vi"
  "deo32RGBA\020\004*\220\001\n\031ESystemAudioPortDirectio"
  "n\022&\n\"k_SystemAudioPortDirection_Invalid\020"
  "\000\022$\n k_SystemAudioPortDirection_Input\020\001\022"
  "%\n!k_SystemAudioPortDirection_Output\020\002*\203"
  "\001\n\023ESystemServiceState\022%\n!k_ESystemServi"
  "ceState_Unavailable\020\000\022\"\n\036k_ESystemServic"
  "eState_Disabled\020\001\022!\n\035k_ESystemServiceSta"
  "te_Enabled\020\002*\341\001\n\031EGraphicsPerfOverlayLev"
  "el\022&\n\"k_EGraphicsPerfOverlayLevel_Hidden"
  "\020\000\022%\n!k_EGraphicsPerfOverlayLevel_Basic\020"
  "\001\022&\n\"k_EGraphicsPerfOverlayLevel_Medium\020"
  "\002\022$\n k_EGraphicsPerfOverlayLevel_Full\020\003\022"
  "\'\n#k_EGraphicsPerfOverlayLevel_Minimal\020\004"
  "*\345\001\n\024EGPUPerformanceLevel\022\"\n\036k_EGPUPerfo"
  "rmanceLevel_Invalid\020\000\022\037\n\033k_EGPUPerforman"
  "ceLevel_Auto\020\001\022!\n\035k_EGPUPerformanceLevel"
  "_Manual\020\002\022\036\n\032k_EGPUPerformanceLevel_Low\020"
  "\003\022\037\n\033k_EGPUPerformanceLevel_High\020\004\022$\n k_"
  "EGPUPerformanceLevel_Profiling\020\005*\310\001\n\023ESp"
  "litScalingFilter\022!\n\035k_ESplitScalingFilte"
  "r_Invalid\020\000\022 \n\034k_ESplitScalingFilter_Lin"
  "ear\020\001\022!\n\035k_ESplitScalingFilter_Nearest\020\002"
  "\022\037\n\033k_ESplitScalingFilter_Sharp\020\003\022(\n$k_E"
  "SplitScalingFilter_NIS_Deprecated\020\004*\335\001\n\023"
  "ESplitScalingScaler\022!\n\035k_ESplitScalingSc"
  "aler_Invalid\020\000\022\036\n\032k_ESplitScalingScaler_"
  "Auto\020\001\022!\n\035k_ESplitScalingScaler_Integer\020"
  "\002\022\035\n\031k_ESplitScalingScaler_Fit\020\003\022\036\n\032k_ES"
  "plitScalingScaler_Fill\020\004\022!\n\035k_ESplitScal"
  "ingScaler_Stretch\020\005*}\n\022EGamescopeBlurMod"
  "e\022!\n\035k_EGamescopeBlurMode_Disabled\020\000\022#\n\037"
  "k_EGamescopeBlurMode_IfOccluded\020\001\022\037\n\033k_E"
  "GamescopeBlurMode_Always\020\002*\304\001\n\nESLSHelpe"
  "r\022\030\n\024k_ESLSHelper_Invalid\020\000\022\031\n\025k_ESLSHel"
  "per_Minidump\020\001\022\026\n\022k_ESLSHelper_Kdump\020\002\022\030"
  "\n\024k_ESLSHelper_Journal\020\003\022\024\n\020k_ESLSHelper"
  "_Gpu\020\004\022\033\n\027k_ESLSHelper_SystemInfo\020\005\022\034\n\030k"
  "_ESLSHelper_Devcoredump\020\006*\305\001\n\021EHDRVisual"
  "ization\022\034\n\030k_EHDRVisualization_None\020\000\022\037\n"
  "\033k_EHDRVisualization_Heatmap\020\001\022 \n\034k_EHDR"
  "Visualization_Analysis\020\002\022\'\n#k_EHDRVisual"
  "ization_HeatmapExtended\020\003\022&\n\"k_EHDRVisua"
  "lization_HeatmapClassic\020\004*\201\001\n\023EHDRToneMa"
  "pOperator\022!\n\035k_EHDRToneMapOperator_Inval"
  "id\020\000\022#\n\037k_EHDRToneMapOperator_Uncharted\020"
  "\001\022\"\n\036k_EHDRToneMapOperator_Reinhard\020\002*|\n"
  "\014ECPUGovernor\022\032\n\026k_ECPUGovernor_Invalid\020"
  "\000\022\027\n\023k_ECPUGovernor_Perf\020\001\022\034\n\030k_ECPUGove"
  "rnor_Powersave\020\002\022\031\n\025k_ECPUGovernor_Manua"
  "l\020\003*\342\001\n\014EUpdaterType\022\032\n\026k_EUpdaterType_I"
  "nvalid\020\000\022\031\n\025k_EUpdaterType_Client\020\001\022\025\n\021k"
  "_EUpdaterType_OS\020\002\022\027\n\023k_EUpdaterType_BIO"
  "S\020\003\022\035\n\031k_EUpdaterType_Aggregated\020\004\022\030\n\024k_"
  "EUpdaterType_Test1\020\005\022\030\n\024k_EUpdaterType_T"
  "est2\020\006\022\030\n\024k_EUpdaterType_Dummy\020\007*\227\002\n\rEUp"
  "daterState\022\033\n\027k_EUpdaterState_Invalid\020\000\022"
  "\034\n\030k_EUpdaterState_UpToDate\020\002\022\034\n\030k_EUpda"
  "terState_Checking\020\003\022\035\n\031k_EUpdaterState_A"
  "vailable\020\004\022\034\n\030k_EUpdaterState_Applying\020\005"
  "\022(\n$k_EUpdaterState_ClientRestartPending"
  "\020\006\022(\n$k_EUpdaterState_SystemRestartPendi"
  "ng\020\007\022\034\n\030k_EUpdaterState_RollBack\020\010*\341\001\n\030E"
  "StorageBlockContentType\022&\n\"k_EStorageBlo"
  "ckContentType_Invalid\020\000\022&\n\"k_EStorageBlo"
  "ckContentType_Unknown\020\001\022)\n%k_EStorageBlo"
  "ckContentType_FileSystem\020\002\022%\n!k_EStorage"
  "BlockContentType_Crypto\020\003\022#\n\037k_EStorageB"
  "lockContentType_Raid\020\004*\303\001\n\033EStorageBlock"
  "FileSystemType\022)\n%k_EStorageBlockFileSys"
  "temType_Invalid\020\000\022)\n%k_EStorageBlockFile"
  "SystemType_Unknown\020\001\022&\n\"k_EStorageBlockF"
  "ileSystemType_VFat\020\002\022&\n\"k_EStorageBlockF"
  "ileSystemType_Ext4\020\003*\320\001\n\026EStorageDriveMe"
  "diaType\022$\n k_EStorageDriveMediaType_Inva"
  "lid\020\000\022$\n k_EStorageDriveMediaType_Unknow"
  "n\020\001\022 \n\034k_EStorageDriveMediaType_HDD\020\002\022 \n"
  "\034k_EStorageDriveMediaType_SSD\020\003\022&\n\"k_ESt"
  "orageDriveMediaType_Removable\020\004*\263\001\n\037ESys"
  "temDisplayCompatibilityMode\022-\n)k_ESystem"
  "DisplayCompatibilityMode_Invalid\020\000\022*\n&k_"
  "ESystemDisplayCompatibilityMode_None\020\001\0225"
  "\n1k_ESystemDisplayCompatibilityMode_Mini"
  "malBandwith\020\002*\255\001\n\035ESteamOSCompatibilityC"
  "ategory\022+\n\'k_ESteamOSCompatibilityCatego"
  "ry_Unknown\020\000\022/\n+k_ESteamOSCompatibilityC"
  "ategory_Unsupported\020\001\022.\n*k_ESteamOSCompa"
  "tibilityCategory_Compatible\020\002*\217\002\n&ESteam"
  "OSCompatibilityResultDisplayType\0226\n2k_ES"
  "teamOSCompatibilityResultDisplayType_Inv"
  "isible\020\000\022:\n6k_ESteamOSCompatibilityResul"
  "tDisplayType_Informational\020\001\0228\n4k_ESteam"
  "OSCompatibilityResultDisplayType_Unsuppo"
  "rted\020\002\0227\n3k_ESteamOSCompatibilityResultD"
  "isplayType_Compatible\020\003*\343\001\n\037ESteamDeckCo"
  "mpatibilityCategory\022-\n)k_ESteamDeckCompa"
  "tibilityCategory_Unknown\020\000\0221\n-k_ESteamDe"
  "ckCompatibilityCategory_Unsupported\020\001\022.\n"
  "*k_ESteamDeckCompatibilityCategory_Playa"
  "ble\020\002\022.\n*k_ESteamDeckCompatibilityCatego"
  "ry_Verified\020\003*\320\002\n(ESteamDeckCompatibilit"
  "yResultDisplayType\0228\n4k_ESteamDeckCompat"
  "ibilityResultDisplayType_Invisible\020\000\022<\n8"
  "k_ESteamDeckCompatibilityResultDisplayTy"
  "pe_Informational\020\001\022:\n6k_ESteamDeckCompat"
  "ibilityResultDisplayType_Unsupported\020\002\0227"
  "\n3k_ESteamDeckCompatibilityResultDisplay"
  "Type_Playable\020\003\0227\n3k_ESteamDeckCompatibi"
  "lityResultDisplayType_Verified\020\004*\232\002\n!ESt"
  "eamDeckCompatibilityTestResult\022/\n+k_ESte"
  "amDeckCompatibilityTestResult_Invalid\020\000\022"
  "5\n1k_ESteamDeckCompatibilityTestResult_N"
  "otApplicable\020\001\022,\n(k_ESteamDeckCompatibil"
  "ityTestResult_Pass\020\002\022,\n(k_ESteamDeckComp"
  "atibilityTestResult_Fail\020\003\0221\n-k_ESteamDe"
  "ckCompatibilityTestResult_FailMinor\020\004*w\n"
  "\010EACState\022\026\n\022k_EACState_Unknown\020\000\022\033\n\027k_E"
  "ACState_Disconnected\020\001\022\030\n\024k_EACState_Con"
  "nected\020\002\022\034\n\030k_EACState_ConnectedSlow\020\003*\205"
  "\001\n\rEBatteryState\022\033\n\027k_EBatteryState_Unkn"
  "own\020\000\022\037\n\033k_EBatteryState_Discharging\020\001\022\034"
  "\n\030k_EBatteryState_Charging\020\002\022\030\n\024k_EBatte"
  "ryState_Full\020\003*\376\001\n\tEOSBranch\022\027\n\023k_EOSBra"
  "nch_Unknown\020\000\022\027\n\023k_EOSBranch_Release\020\001\022 "
  "\n\034k_EOSBranch_ReleaseCandidate\020\002\022\024\n\020k_EO"
  "SBranch_Beta\020\003\022\035\n\031k_EOSBranch_BetaCandid"
  "ate\020\004\022\027\n\023k_EOSBranch_Preview\020\005\022 \n\034k_EOSB"
  "ranch_PreviewCandidate\020\006\022\024\n\020k_EOSBranch_"
  "Main\020\007\022\027\n\023k_EOSBranch_Staging\020\010*\306\003\n\021EBro"
  "wserGPUStatus\022\037\n\033k_EBrowserGPUStatus_Inv"
  "alid\020\000\022\037\n\033k_EBrowserGPUStatus_Enabled\020\001\022"
  "\'\n#k_EBrowserGPUStatus_DisabledUnknown\020\002"
  "\022*\n&k_EBrowserGPUStatus_DisabledCrashCou"
  "nt\020\004\022)\n%k_EBrowserGPUStatus_DisabledBloc"
  "klist\020\005\022)\n%k_EBrowserGPUStatus_DisabledJ"
  "SRequest\020\006\022+\n\'k_EBrowserGPUStatus_Disabl"
  "edCommandLine\020\007\022-\n)k_EBrowserGPUStatus_D"
  "isabledRuntimeDetect\020\010\0220\n,k_EBrowserGPUS"
  "tatus_DisabledChildCommandLine\020\t\0226\n2k_EB"
  "rowserGPUStatus_DisabledCompositingComma"
  "ndLine\020\n*\343\004\n\025EBrowserFeatureStatus\022#\n\037k_"
  "EBrowserFeatureStatus_Invalid\020\000\022$\n k_EBr"
  "owserFeatureStatus_NotFound\020\001\022#\n\037k_EBrow"
  "serFeatureStatus_Unknown\020\002\022,\n(k_EBrowser"
  "FeatureStatus_DisabledSoftware\020\003\022\'\n#k_EB"
  "rowserFeatureStatus_DisabledOff\020\004\022)\n%k_E"
  "BrowserFeatureStatus_DisabledOffOk\020\005\022/\n+"
  "k_EBrowserFeatureStatus_UnavailableSoftw"
  "are\020\006\022*\n&k_EBrowserFeatureStatus_Unavail"
  "ableOff\020\007\022,\n(k_EBrowserFeatureStatus_Una"
  "vailableOffOk\020\010\022+\n\'k_EBrowserFeatureStat"
  "us_EnabledReadback\020\t\022(\n$k_EBrowserFeatur"
  "eStatus_EnabledForce\020\n\022#\n\037k_EBrowserFeat"
  "ureStatus_Enabled\020\013\022%\n!k_EBrowserFeature"
  "Status_EnabledOn\020\014\022*\n&k_EBrowserFeatureS"
  "tatus_EnabledForceOn\020\r*\237\005\n\014EGpuDriverId\022"
  "\032\n\026k_EGpuDriverId_Invalid\020\000\022\032\n\026k_EGpuDri"
  "verId_Unknown\020\001\022!\n\035k_EGpuDriverId_AmdPro"
  "prietary\020\002\022 \n\034k_EGpuDriverId_AmdOpenSour"
  "ce\020\003\022\033\n\027k_EGpuDriverId_MesaRadv\020\004\022$\n k_E"
  "GpuDriverId_NvidiaProprietary\020\005\022\"\n\036k_EGp"
  "uDriverId_IntelPropietary\020\006\022\034\n\030k_EGpuDri"
  "verId_MesaIntel\020\007\022&\n\"k_EGpuDriverId_Qual"
  "commProprietary\020\010\022!\n\035k_EGpuDriverId_ArmP"
  "roprietary\020\t\022$\n k_EGpuDriverId_GoogleSwi"
  "ftshader\020\n\022&\n\"k_EGpuDriverId_BroadcomPro"
  "prietary\020\013\022\037\n\033k_EGpuDriverId_MesaLLVMPip"
  "e\020\014\022\033\n\027k_EGpuDriverId_MoltenVK\020\r\022\035\n\031k_EG"
  "puDriverId_MesaTurnip\020\016\022\034\n\030k_EGpuDriverI"
  "d_MesaPanVK\020\017\022\034\n\030k_EGpuDriverId_MesaVenu"
  "s\020\020\022\034\n\030k_EGpuDriverId_MesaDozen\020\021\022\032\n\026k_E"
  "GpuDriverId_MesaNVK\020\022\022!\n\035k_EGpuDriverId_"
  "MesaHoneyKrisp\020\023*\335\005\n\023ECommunityItemClass"
  "\022!\n\035k_ECommunityItemClass_Invalid\020\000\022\037\n\033k"
  "_ECommunityItemClass_Badge\020\001\022\"\n\036k_ECommu"
  "nityItemClass_GameCard\020\002\022+\n\'k_ECommunity"
  "ItemClass_ProfileBackground\020\003\022\"\n\036k_EComm"
  "unityItemClass_Emoticon\020\004\022%\n!k_ECommunit"
  "yItemClass_BoosterPack\020\005\022$\n k_ECommunity"
  "ItemClass_Consumable\020\006\022!\n\035k_ECommunityIt"
  "emClass_GameGoo\020\007\022)\n%k_ECommunityItemCla"
  "ss_ProfileModifier\020\010\022\037\n\033k_ECommunityItem"
  "Class_Scene\020\t\022$\n k_ECommunityItemClass_S"
  "alienItem\020\n\022!\n\035k_ECommunityItemClass_Sti"
  "cker\020\013\022$\n k_ECommunityItemClass_ChatEffe"
  "ct\020\014\022/\n+k_ECommunityItemClass_MiniProfil"
  "eBackground\020\r\022%\n!k_ECommunityItemClass_A"
  "vatarFrame\020\016\022(\n$k_ECommunityItemClass_An"
  "imatedAvatar\020\017\022/\n+k_ECommunityItemClass_"
  "SteamDeckKeyboardSkin\020\020\022/\n+k_ECommunityI"
  "temClass_SteamDeckStartupMovie\020\021*\331\001\n\037ESt"
  "eamDeckCompatibilityFeedback\022+\n\'k_ESteam"
  "DeckCompatibilityFeedback_Unset\020\000\022+\n\'k_E"
  "SteamDeckCompatibilityFeedback_Agree\020\001\022."
  "\n*k_ESteamDeckCompatibilityFeedback_Disa"
  "gree\020\002\022,\n(k_ESteamDeckCompatibilityFeedb"
  "ack_Ignore\020\003*\237\001\n\036EProvideDeckFeedbackPre"
  "ference\022*\n&k_EProvideDeckFeedbackPrefere"
  "nce_Unset\020\000\022(\n$k_EProvideDeckFeedbackPre"
  "ference_Yes\020\001\022\'\n#k_EProvideDeckFeedbackP"
  "reference_No\020\002*\350\002\n%EHardwareCompatibilit"
  "yFeedbackDetails\0221\n-k_EHardwareCompatibi"
  "lityFeedbackDetails_Unset\020\000\0227\n3k_EHardwa"
  "reCompatibilityFeedbackDetails_Performan"
  "ce\020\001\0225\n1k_EHardwareCompatibilityFeedback"
  "Details_Stability\020\002\0226\n2k_EHardwareCompat"
  "ibilityFeedbackDetails_Legibility\020\004\0221\n-k"
  "_EHardwareCompatibilityFeedbackDetails_I"
  "nput\020\010\0221\n-k_EHardwareCompatibilityFeedba"
  "ckDetails_Other\020\020*\357\001\n!EGameFrameRateRepo"
  "rtingPreference\022-\n)k_EGameFrameRateRepor"
  "tingPreference_Unset\020\000\022*\n&k_EGameFrameRa"
  "teReportingPreference_No\020\001\0225\n1k_EGameFra"
  "meRateReportingPreference_Yes_Anonymous\020"
  "\002\0228\n4k_EGameFrameRateReportingPreference"
  "_Yes_NonAnonymous\020\003*\261\003\n\rETouchGesture\022\027\n"
  "\023k_ETouchGestureNone\020\000\022\030\n\024k_ETouchGestur"
  "eTouch\020\001\022\026\n\022k_ETouchGestureTap\020\002\022\034\n\030k_ET"
  "ouchGestureDoubleTap\020\003\022\035\n\031k_ETouchGestur"
  "eShortPress\020\004\022\034\n\030k_ETouchGestureLongPres"
  "s\020\005\022\032\n\026k_ETouchGestureLongTap\020\006\022\037\n\033k_ETo"
  "uchGestureTwoFingerTap\020\007\022\037\n\033k_ETouchGest"
  "ureTapCancelled\020\010\022\035\n\031k_ETouchGesturePinc"
  "hBegin\020\t\022\036\n\032k_ETouchGesturePinchUpdate\020\n"
  "\022\033\n\027k_ETouchGesturePinchEnd\020\013\022\035\n\031k_ETouc"
  "hGestureFlingStart\020\014\022!\n\035k_ETouchGestureF"
  "lingCancelled\020\r*\214\001\n\023ESessionPersistence\022"
  "*\n\035k_ESessionPersistence_Invalid\020\377\377\377\377\377\377\377"
  "\377\377\001\022#\n\037k_ESessionPersistence_Ephemeral\020\000"
  "\022$\n k_ESessionPersistence_Persistent\020\001*\331"
  "\001\n\032ENewSteamAnnouncementState\022(\n$k_ENewS"
  "teamAnnouncementState_Invalid\020\000\022(\n$k_ENe"
  "wSteamAnnouncementState_AllRead\020\001\0220\n,k_E"
  "NewSteamAnnouncementState_NewAnnouncemen"
  "t\020\002\0225\n1k_ENewSteamAnnouncementState_Feat"
  "uredAnnouncement\020\003*\376\001\n\nEForumType\022\030\n\024k_E"
  "ForumType_Invalid\020\000\022\030\n\024k_EForumType_Gene"
  "ral\020\001\022\036\n\032k_EForumType_ReportedPosts\020\002\022\031\n"
  "\025k_EForumType_Workshop\020\003\022\036\n\032k_EForumType"
  "_PublishedFile\020\004\022\030\n\024k_EForumType_Trading"
  "\020\005\022\031\n\025k_EForumType_PlayTest\020\006\022\026\n\022k_EForu"
  "mType_Event\020\007\022\024\n\020k_EForumType_Max\020\010*\213\007\n\022"
  "ECommentThreadType\022\037\n\033k_ECommentThreadTy"
  "peInvalid\020\000\022-\n)k_ECommentThreadTypeScree"
  "nshot_Deprecated\020\001\0221\n-k_ECommentThreadTy"
  "peWorkshopAccount_Developer\020\002\022.\n*k_EComm"
  "entThreadTypeWorkshopAccount_Public\020\003\022/\n"
  "+k_ECommentThreadTypePublishedFile_Devel"
  "oper\020\004\022,\n(k_ECommentThreadTypePublishedF"
  "ile_Public\020\005\022\034\n\030k_ECommentThreadTypeTest"
  "\020\006\022\"\n\036k_ECommentThreadTypeForumTopic\020\007\022&"
  "\n\"k_ECommentThreadTypeRecommendation\020\010\022("
  "\n$k_ECommentThreadTypeVideo_Deprecated\020\t"
  "\022\037\n\033k_ECommentThreadTypeProfile\020\n\022 \n\034k_E"
  "CommentThreadTypeNewsPost\020\013\022\034\n\030k_ECommen"
  "tThreadTypeClan\020\014\022(\n$k_ECommentThreadTyp"
  "eClanAnnouncement\020\r\022!\n\035k_ECommentThreadT"
  "ypeClanEvent\020\016\022+\n\'k_ECommentThreadTypeUs"
  "erStatusPublished\020\017\022+\n\'k_ECommentThreadT"
  "ypeUserReceivedNewGame\020\020\0222\n.k_ECommentTh"
  "readTypePublishedFile_Announcement\020\021\022(\n$"
  "k_ECommentThreadTypeModeratorMessage\020\022\022&"
  "\n\"k_ECommentThreadTypeClanCuratedApp\020\023\022$"
  "\n k_ECommentThreadTypeQAndASession\020\024\022\033\n\027"
  "k_ECommentThreadTypeMax\020\025*\327\001\n\024EBroadcast"
  "Permission\022\"\n\036k_EBroadcastPermissionDisa"
  "bled\020\000\022(\n$k_EBroadcastPermissionFriendsA"
  "pprove\020\001\022(\n$k_EBroadcastPermissionFriend"
  "sAllowed\020\002\022 \n\034k_EBroadcastPermissionPubl"
  "ic\020\003\022%\n!k_EBroadcastPermissionSubscriber"
  "s\020\004*f\n\030EBroadcastEncoderSetting\022\"\n\036k_EBr"
  "oadcastEncoderBestQuality\020\000\022&\n\"k_EBroadc"
  "astEncoderBestPerformance\020\001*y\n\024ECloudGam"
  "ingPlatform\022\036\n\032k_ECloudGamingPlatformNon"
  "e\020\000\022\037\n\033k_ECloudGamingPlatformValve\020\001\022 \n\034"
  "k_ECloudGamingPlatformNVIDIA\020\002*\355\002\n\030EComp"
  "romiseDetectionType\022#\n\037k_ECompromiseDete"
  "ctionType_None\020\000\022)\n%k_ECompromiseDetecti"
  "onType_TradeEvent\020\001\022*\n&k_ECompromiseDete"
  "ctionType_ApiCallRate\020\002\022%\n!k_ECompromise"
  "DetectionType_Manual\020\003\022+\n\'k_ECompromiseD"
  "etectionType_TicketAction\020\004\022.\n*k_ECompro"
  "miseDetectionType_MaliciousRefund\020\005\022&\n\"k"
  "_ECompromiseDetectionType_Move2FA\020\006\022)\n%k"
  "_ECompromiseDetectionType_DeviceType\020\007*\326"
  "\001\n\032EAsyncGameSessionUserState\0220\n#k_EAsyn"
  "cGameSessionUserStateUnknown\020\377\377\377\377\377\377\377\377\377\001\022"
  "0\n,k_EAsyncGameSessionUserStateWaitingFo"
  "rOthers\020\000\022.\n*k_EAsyncGameSessionUserStat"
  "eReadyForAction\020\001\022$\n k_EAsyncGameSession"
  "UserStateDone\020\002*\304\001\n\037EAsyncGameSessionUse"
  "rVisibility\022;\n7k_EAsyncGameSessionUserVi"
  "sibilityEnvelopeAndSessionList\020\000\0224\n0k_EA"
  "syncGameSessionUserVisibilitySessionList"
  "Only\020\001\022.\n*k_EAsyncGameSessionUserVisibil"
  "ityDismissed\020\002*\324\001\n\022EGameRecordingType\022 \n"
  "\034k_EGameRecordingType_Unknown\020\000\022%\n!k_EGa"
  "meRecordingType_NotRecording\020\001\022(\n$k_EGam"
  "eRecordingType_ManualRecording\020\002\022,\n(k_EG"
  "ameRecordingType_BackgroundRecording\020\003\022\035"
  "\n\031k_EGameRecordingType_Clip\020\004*J\n\007EGRMode"
  "\022\023\n\017k_EGRMode_Never\020\000\022\024\n\020k_EGRMode_Alway"
  "s\020\001\022\024\n\020k_EGRMode_Manual\020\002*\\\n\014EExportCode"
  "c\022\032\n\026k_EExportCodec_Default\020\000\022\027\n\023k_EExpo"
  "rtCodec_H264\020\001\022\027\n\023k_EExportCodec_H265\020\002*"
  "\352\003\n\rEProtoAppType\022\025\n\021k_EAppTypeInvalid\020\000"
  "\022\022\n\016k_EAppTypeGame\020\001\022\031\n\025k_EAppTypeApplic"
  "ation\020\002\022\022\n\016k_EAppTypeTool\020\004\022\022\n\016k_EAppTyp"
  "eDemo\020\010\022\027\n\023k_EAppTypeDeprected\020\020\022\021\n\rk_EA"
  "ppTypeDLC\020 \022\023\n\017k_EAppTypeGuide\020@\022\025\n\020k_EA"
  "ppTypeDriver\020\200\001\022\025\n\020k_EAppTypeConfig\020\200\002\022\027"
  "\n\022k_EAppTypeHardware\020\200\004\022\030\n\023k_EAppTypeFra"
  "nchise\020\200\010\022\024\n\017k_EAppTypeVideo\020\200\020\022\025\n\020k_EAp"
  "pTypePlugin\020\200 \022\031\n\024k_EAppTypeMusicAlbum\020\200"
  "@\022\026\n\020k_EAppTypeSeries\020\200\200\001\022\025\n\017k_EAppTypeC"
  "omic\020\200\200\002\022\024\n\016k_EAppTypeBeta\020\200\200\004\022\032\n\022k_EApp"
  "TypeShortcut\020\200\200\200\200\004\022 \n\023k_EAppTypeDepotOnl"
  "y\020\200\200\200\200\370\377\377\377\377\001*\211\003\n\014EAppTestType\022\036\n\032k_EAppT"
  "estType_BuildReview\020\000\022\"\n\036k_EAppTestType_"
  "StorePageReview\020\001\022)\n%k_EAppTestType_Stea"
  "mChina_BuildReview\020\002\022-\n)k_EAppTestType_S"
  "teamChina_StorePageReview\020\003\022=\n9k_EAppTes"
  "tType_SteamChinaPlatformOperator_StorePa"
  "geReview\020\004\0229\n5k_EAppTestType_SteamChinaP"
  "latformOperator_BuildReview\020\005\022/\n+k_EAppT"
  "estType_SteamDeckCompatibilityReview\020\006\0220"
  "\n,k_EAppTestType_SteamFrameCompatibility"
  "Review\020\007*\226\001\n\031EChildProcessQueryCommand\022\'"
  "\n#k_EChildProcessQueryCommand_Invalid\020\000\022"
  "+\n\'k_EChildProcessQueryCommand_GpuTopolo"
  "gy\020\001\022#\n\037k_EChildProcessQueryCommand_Max\020"
  "\002*\366\002\n\032EChildProcessQueryExitCode\022(\n$k_EC"
  "hildProcessQueryExitCode_Success\020\000\022:\n-k_"
  "EChildProcessQueryExitCode_ErrorCommandl"
  "ine\020\377\377\377\377\377\377\377\377\377\001\0224\n\'k_EChildProcessQueryEx"
  "itCode_ErrorOther\020\376\377\377\377\377\377\377\377\377\001\022<\n/k_EChild"
  "ProcessQueryExitCode_ErrorUnimplemented\020"
  "\375\377\377\377\377\377\377\377\377\001\0227\n*k_EChildProcessQueryExitCo"
  "de_ErrorFileSave\020\374\377\377\377\377\377\377\377\377\001\022E\n8k_EChildP"
  "rocessQueryExitCode_ErrorNotSupportedByP"
  "latform\020\373\377\377\377\377\377\377\377\377\001*\362\001\n EWindowsUpdateIns"
  "tallationImpact\0227\n*k_EWindowsUpdateInsta"
  "llationImpact_Unknown\020\377\377\377\377\377\377\377\377\377\001\022-\n)k_EW"
  "indowsUpdateInstallationImpact_Normal\020\000\022"
  ",\n(k_EWindowsUpdateInstallationImpact_Mi"
  "nor\020\001\0228\n4k_EWindowsUpdateInstallationImp"
  "act_ExclusiveHandling\020\002*\362\001\n\034EWindowsUpda"
  "teRebootBehavior\0223\n&k_EWindowsUpdateRebo"
  "otBehavior_Unknown\020\377\377\377\377\377\377\377\377\377\001\0223\n/k_EWind"
  "owsUpdateRebootBehavior_NeverNeedsReboot"
  "\020\000\0224\n0k_EWindowsUpdateRebootBehavior_Alw"
  "aysNeedsReboot\020\001\0222\n.k_EWindowsUpdateRebo"
  "otBehavior_MightNeedReboot\020\002*\376\001\n\026EExtern"
  "alSaleEventType\022$\n k_EExternalSaleEventT"
  "ype_Unknown\020\000\022&\n\"k_EExternalSaleEventTyp"
  "e_Publisher\020\001\022%\n!k_EExternalSaleEventTyp"
  "e_Showcase\020\002\022#\n\037k_EExternalSaleEventType"
  "_Region\020\003\022\"\n\036k_EExternalSaleEventType_Th"
  "eme\020\004\022&\n\"k_EExternalSaleEventType_Franch"
  "ise\020\005*\333\001\n\037EEnhancedMarketAppearanceStatu"
  "s\022)\n%k_EnhancedMarketAppearanceStatus_No"
  "ne\020\000\022,\n(k_EnhancedMarketAppearanceStatus"
  "_Pending\020\001\022/\n+k_EnhancedMarketAppearance"
  "Status_InProgress\020\002\022.\n*k_EnhancedMarketA"
  "ppearanceStatus_Completed\020\003*\363\002\n\031EContent"
  "ReportSubjectType\022\'\n#k_EContentReportSub"
  "jectType_Invalid\020\000\022)\n%k_EContentReportSu"
  "bjectType_ForumPost\020\001\022-\n)k_EContentRepor"
  "tSubjectType_CommentThread\020\002\022\'\n#k_EConte"
  "ntReportSubjectType_UGCFile\020\003\022-\n)k_ECont"
  "entReportSubjectType_FriendChatMsg\020\004\022+\n\'"
  "k_EContentReportSubjectType_ChatRoomMsg\020"
  "\005\022)\n%k_EContentReportSubjectType_ChatGro"
  "up\020\006\022#\n\037k_EContentReportSubjectType_MAX\020"
  "\007*\331\001\n\036EControlledLegalCategoryStatus\022)\n%"
  "k_EControlledLegalCategoryStatus_None\020\000\022"
  ",\n(k_EControlledLegalCategoryStatus_Accu"
  "sed\020\001\022.\n*k_EControlledLegalCategoryStatu"
  "s_Convicted\020\002\022.\n*k_EControlledLegalCateg"
  "oryStatus_Acquitted\020\003*\251\001\n\026EContentModera"
  "torLevel\022 \n\034k_EContentModeratorLevel_Any"
  "\020\000\022\'\n#k_EContentModeratorLevel_Superviso"
  "r\020\001\022\"\n\036k_EContentModeratorLevel_Valve\020\n\022"
  " \n\034k_EContentModeratorLevel_MAX\020\013*\313\006\n\030EC"
  "ontentReportResolution\022)\n%k_EContentRepo"
  "rtResolution_Unresolved\020\000\022(\n$k_EContentR"
  "eportResolution_Acquitted\020\001\022&\n\"k_EConten"
  "tReportResolution_Removed\020\002\022)\n%k_EConten"
  "tReportResolution_Relabelled\020\003\022)\n%k_ECon"
  "tentReportResolution_Suspicious\020\004\022/\n+k_E"
  "ContentReportResolution_HarassmentStrike"
  "\020\005\022%\n!k_EContentReportResolution_Purged\020"
  "\006\0222\n.k_EContentReportResolution_Disconne"
  "ctedFromApp\020\007\022:\n6k_EContentReportResolut"
  "ion_SuspiciousIncludingUpvoters\020\010\0220\n,k_E"
  "ContentReportResolution_VisibilityChange"
  "d\020\t\0229\n5k_EContentReportResolution_Countr"
  "yRestrictionsChanged\020\n\022,\n(k_EContentRepo"
  "rtResolution_RemoveAndWarn\020\013\022+\n\'k_EConte"
  "ntReportResolution_RemoveAndBan\020\014\022,\n(k_E"
  "ContentReportResolution_RemoveAndKick\020\r\022"
  ")\n%k_EContentReportResolution_Sanctioned"
  "\020\016\022(\n$k_EContentReportResolution_Sustain"
  "ed\020\017\022%\n!k_EContentReportResolution_Broke"
  "n\020\020\022\"\n\036k_EContentReportResolution_MAX\020\021*"
  "\310\004\n\032EContentModerationSanction\022(\n$k_ECon"
  "tentModerationSanction_Invalid\020\000\022(\n$k_EC"
  "ontentModerationSanction_Deleted\020\001\0220\n,k_"
  "EContentModerationSanction_CommunityBann"
  "ed\020\002\022*\n&k_EContentModerationSanction_Hub"
  "Banned\020\003\022,\n(k_EContentModerationSanction"
  "_TradeBanned\020\004\0226\n2k_EContentModerationSa"
  "nction_CommentHistoryDeleted\020\005\022+\n\'k_ECon"
  "tentModerationSanction_Relabelled\020\006\0221\n-k"
  "_EContentModerationSanction_MarkAsSuspic"
  "ious\020\007\022\'\n#k_EContentModerationSanction_W"
  "arned\020\010\0220\n,k_EContentModerationSanction_"
  "KickedFromGroup\020\t\0221\n-k_EContentModeratio"
  "nSanction_HarassmentBanned\020\n\022$\n k_EConte"
  "ntModerationSanction_MAX\020\013*\377\010\n\033EContentR"
  "eportSubjectAction\022)\n%k_EContentReportSu"
  "bjectAction_Invalid\020\000\022,\n(k_EContentRepor"
  "tSubjectAction_Unresolved\020\001\022,\n(k_EConten"
  "tReportSubjectAction_Sanctioned\020\002\022+\n\'k_E"
  "ContentReportSubjectAction_Acquitted\020\003\022+"
  "\n\'k_EContentReportSubjectAction_Cancelle"
  "d\020\004\022)\n%k_EContentReportSubjectAction_Upd"
  "ated\020\005\022+\n\'k_EContentReportSubjectAction_"
  "Escalated\020\006\022*\n&k_EContentReportSubjectAc"
  "tion_Disputed\020\007\022+\n\'k_EContentReportSubje"
  "ctAction_Sustained\020\010\022(\n$k_EContentReport"
  "SubjectAction_Locked\020\t\022*\n&k_EContentRepo"
  "rtSubjectAction_Unlocked\020\n\022)\n%k_EContent"
  "ReportSubjectAction_Deleted\020\013\022(\n$k_ECont"
  "entReportSubjectAction_Warned\020\014\022/\n+k_ECo"
  "ntentReportSubjectAction_BannedFromHub\020\r"
  "\0225\n1k_EContentReportSubjectAction_Banned"
  "FromCommunity\020\016\022-\n)k_EContentReportSubje"
  "ctAction_TradeBanned\020\017\0224\n0k_EContentRepo"
  "rtSubjectAction_MarkedAsSuspicious\020\020\022.\n*"
  "k_EContentReportSubjectAction_ResetConte"
  "nt\020\021\0222\n.k_EContentReportSubjectAction_Es"
  "calatedForCSAM\020\022\0227\n3k_EContentReportSubj"
  "ectAction_EscalatedForTerrorism\020\023\022)\n%k_E"
  "ContentReportSubjectAction_Claimed\020\024\022*\n&"
  "k_EContentReportSubjectAction_Released\020\025"
  "\0221\n-k_EContentReportSubjectAction_Privat"
  "eMessaged\020\026\022/\n+k_EContentReportSubjectAc"
  "tion_OwnerDisputed\020\027*\335\030\n\024EContentReportR"
  "eason\022\"\n\036k_EContentReportReason_Invalid\020"
  "\000\022\037\n\033k_EContentReportReason_None\020\001\022\"\n\036k_"
  "EContentReportReason_Unknown\020\002\022%\n!k_ECon"
  "tentReportReason_Harassment\020\003\0222\n.k_ECont"
  "entReportReason_BullyingAndIntimidation\020"
  "\004\022#\n\037k_EContentReportReason_Stalking\020\005\022\""
  "\n\036k_EContentReportReason_Doxxing\020\006\022*\n&k_"
  "EContentReportReason_OtherHarassment\020\007\022."
  "\n*k_EContentReportReason_EncouragingViol"
  "ence\020\010\022.\n*k_EContentReportReason_Encoura"
  "gingSelfHarm\020\t\022-\n)k_EContentReportReason"
  "_EncouragingSuicide\020\n\0222\n.k_EContentRepor"
  "tReason_OtherViolenceOrSelfHarm\020\013\0221\n-k_E"
  "ContentReportReason_PhishingOrAccountThe"
  "ft\020\014\022,\n(k_EContentReportReason_Attempted"
  "Scamming\020\r\0224\n0k_EContentReportReason_Lin"
  "kingToMaliciousContent\020\016\022(\n$k_EContentRe"
  "portReason_Impersonation\020\017\022-\n)k_EContent"
  "ReportReason_OtherScamsAndTheft\020\020\022/\n+k_E"
  "ContentReportReason_EncouragingTerrorism"
  "\020\021\022.\n*k_EContentReportReason_OrganizingT"
  "errorism\020\022\022)\n%k_EContentReportReason_Oth"
  "erTerrorism\020\023\022(\n$k_EContentReportReason_"
  "TargetedAbuse\020\024\022+\n\'k_EContentReportReaso"
  "n_NamingAndShaming\020\025\022)\n%k_EContentReport"
  "Reason_Discrimination\020\026\022%\n!k_EContentRep"
  "ortReason_OtherAbuse\020\027\022#\n\037k_EContentRepo"
  "rtReason_Trolling\020\030\022\"\n\036k_EContentReportR"
  "eason_Baiting\020\031\022$\n k_EContentReportReaso"
  "n_Derailing\020\032\022*\n&k_EContentReportReason_"
  "OtherDisruptive\020\033\022\037\n\033k_EContentReportRea"
  "son_Spam\020\034\022\"\n\036k_EContentReportReason_Beg"
  "ging\020\035\022$\n k_EContentReportReason_Reposti"
  "ng\020\036\022(\n$k_EContentReportReason_OtherOffT"
  "opic\020\037\022,\n(k_EContentReportReason_CSAMSex"
  "ualContent\020 \0223\n/k_EContentReportReason_C"
  "SAMGroomingOrEnticement\020!\022$\n k_EContentR"
  "eportReason_CSAMOther\020\"\0220\n,k_EContentRep"
  "ortReason_NudityOrSexualContent\020#\0220\n,k_E"
  "ContentReportReason_NonConsensualMateria"
  "l\020$\022&\n\"k_EContentReportReason_Advertisin"
  "g\020%\022(\n$k_EContentReportReason_ReferralLi"
  "nks\020&\022#\n\037k_EContentReportReason_Gambling"
  "\020\'\022\"\n\036k_EContentReportReason_Raffles\020(\0222"
  "\n.k_EContentReportReason_OtherCommercial"
  "Activity\020)\022,\n(k_EContentReportReason_Ina"
  "uthenticReview\020*\022G\nCk_EContentReportReas"
  "on_HiddenAdvertisementOrCommercialCommun"
  "ication\020+\022D\n@k_EContentReportReason_Misl"
  "eadingInformationAboutGoodsOrServices\020,\022"
  "C\n\?k_EContentReportReason_MisleadingInfo"
  "rmationAboutConsumerRights\020-\022>\n:k_EConte"
  "ntReportReason_NoncomplianceWithPricingR"
  "egulations\020.\0226\n2k_EContentReportReason_R"
  "ightToBeForgottenViolation\020/\0229\n5k_EConte"
  "ntReportReason_MissingProcessingGroundFo"
  "rData\0200\022A\n=k_EContentReportReason_OtherD"
  "ataProtectionAndPrivacyViolation\0201\022-\n)k_"
  "EContentReportReason_GenderedHarassment\020"
  "2\022:\n6k_EContentReportReason_GenderedBull"
  "yingAndIntimidation\0203\022+\n\'k_EContentRepor"
  "tReason_GenderedStalking\0204\022*\n&k_EContent"
  "ReportReason_GenderedDoxxing\0205\0222\n.k_ECon"
  "tentReportReason_GenderedOtherHarassment"
  "\0206\0226\n2k_EContentReportReason_GenderedEnc"
  "ouragingViolence\0207\0220\n,k_EContentReportRe"
  "ason_GenderedTargetedAbuse\0208\0221\n-k_EConte"
  "ntReportReason_CSAMFakedSexualContent\0209\022"
  "8\n4k_EContentReportReason_GenderedNonCon"
  "sensualMaterial\020:\022=\n9k_EContentReportRea"
  "son_FakedGenderedNonConsensualMaterial\020;"
  "\0225\n1k_EContentReportReason_FakedNonConse"
  "nsualMaterial\020<\022\?\n;k_EContentReportReaso"
  "n_NegativeEffectonDiscourseOrElections\020="
  "\0221\n-k_EContentReportReason_QuotesModerat"
  "edContent\020>\0223\n/k_EContentReportReason_Cr"
  "edibleThreatOfViolence\020\?\0222\n.k_EContentRe"
  "portReason_AutoCreatedOnModeration\020@\022\036\n\032"
  "k_EContentReportReason_MAX\020A*\270\001\n\025EResolu"
  "tionAutomation\022\"\n\036k_EResolutionAutomatio"
  "n_Manual\020\000\022.\n*k_EResolutionAutomation_Pa"
  "rtiallyAutomated\020\001\022*\n&k_EResolutionAutom"
  "ation_FullyAutomated\020\002\022\037\n\033k_EResolutionA"
  "utomation_MAX\020\003*\223\004\n\022EPressOutletAction\022 "
  "\n\034k_EPressOutletAction_Invalid\020\000\022 \n\034k_EP"
  "ressOutletAction_Granted\020\001\022 \n\034k_EPressOu"
  "tletAction_Removed\020\002\022 \n\034k_EPressOutletAc"
  "tion_Created\020\003\022 \n\034k_EPressOutletAction_U"
  "pdated\020\004\022 \n\034k_EPressOutletAction_Deleted"
  "\020\005\022\"\n\036k_EPressOutletAction_Undeleted\020\006\022\""
  "\n\036k_EPressOutletAction_StagedAdd\020\007\022%\n!k_"
  "EPressOutletAction_StagedDelete\020\010\022%\n!k_E"
  "PressOutletAction_EnterStaging\020\t\022$\n k_EP"
  "ressOutletAction_ExitStaging\020\n\022)\n%k_EPre"
  "ssOutletAction_ReverseStagedAdd\020\013\022,\n(k_E"
  "PressOutletAction_ReverseStagedDelete\020\014\022"
  "\034\n\030k_EPressOutletAction_MAX\020\r*\332\001\n\036EPress"
  "OutletMemberPendingState\022+\n\'k_EPressOutl"
  "etMemberPendingState_Member\020\000\0221\n-k_EPres"
  "sOutletMemberPendingState_StagedDelete\020\001"
  "\022.\n*k_EPressOutletMemberPendingState_Sta"
  "gedAdd\020\002\022(\n$k_EPressOutletMemberPendingS"
  "tate_MAX\020\003*\232\002\n\024ECommentDeleteReason\022\"\n\036k"
  "_ECommentDeleteReason_Invalid\020\000\022\037\n\033k_ECo"
  "mmentDeleteReason_User\020\001\022&\n\"k_ECommentDe"
  "leteReason_ThreadOwner\020\002\022$\n k_ECommentDe"
  "leteReason_Moderator\020\003\022\"\n\036k_ECommentDele"
  "teReason_Support\020\004\022\037\n\033k_ECommentDeleteRe"
  "ason_Spam\020\005\022*\n&k_ECommentDeleteReason_Ac"
  "countDeletion\020\006"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_enums_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_enums_2eproto = {
  false, false, 28775, descriptor_table_protodef_enums_2eproto, "enums.proto", 
  &descriptor_table_enums_2eproto_once, nullptr, 0, 0,
  schemas, file_default_instances, TableStruct_enums_2eproto::offsets,
  file_level_metadata_enums_2eproto, file_level_enum_descriptors_enums_2eproto, file_level_service_descriptors_enums_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK ::PROTOBUF_NAMESPACE_ID::Metadata
descriptor_table_enums_2eproto_metadata_getter(int index) {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return descriptor_table_enums_2eproto.file_level_metadata[index];
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_enums_2eproto(&descriptor_table_enums_2eproto);
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EPublishedFileQueryType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[0];
}
bool EPublishedFileQueryType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EPublishedFileInappropriateProvider_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[1];
}
bool EPublishedFileInappropriateProvider_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EPublishedFileInappropriateResult_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[2];
}
bool EPublishedFileInappropriateResult_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 30:
    case 50:
    case 75:
    case 100:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EPersonaStateFlag_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[3];
}
bool EPersonaStateFlag_IsValid(int value) {
  switch (value) {
    case 1:
    case 2:
    case 4:
    case 8:
    case 256:
    case 512:
    case 1024:
    case 2048:
    case 4096:
    case 8192:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EContentCheckProvider_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[4];
}
bool EContentCheckProvider_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EProfileCustomizationType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[5];
}
bool EProfileCustomizationType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EPublishedFileStorageSystem_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[6];
}
bool EPublishedFileStorageSystem_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ECloudStoragePersistState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[7];
}
bool ECloudStoragePersistState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESDCardFormatStage_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[8];
}
bool ESDCardFormatStage_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EStorageFormatStage_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[9];
}
bool EStorageFormatStage_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESystemFanControlMode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[10];
}
bool ESystemFanControlMode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EColorGamutLabelSet_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[11];
}
bool EColorGamutLabelSet_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EWindowStackingOrder_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[12];
}
bool EWindowStackingOrder_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EBluetoothDeviceType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[13];
}
bool EBluetoothDeviceType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESpeakerConfiguration_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[14];
}
bool ESpeakerConfiguration_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESystemAudioDirection_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[15];
}
bool ESystemAudioDirection_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESystemAudioChannel_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[16];
}
bool ESystemAudioChannel_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESystemAudioPortType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[17];
}
bool ESystemAudioPortType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESystemAudioPortDirection_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[18];
}
bool ESystemAudioPortDirection_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESystemServiceState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[19];
}
bool ESystemServiceState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGraphicsPerfOverlayLevel_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[20];
}
bool EGraphicsPerfOverlayLevel_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGPUPerformanceLevel_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[21];
}
bool EGPUPerformanceLevel_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESplitScalingFilter_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[22];
}
bool ESplitScalingFilter_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESplitScalingScaler_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[23];
}
bool ESplitScalingScaler_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGamescopeBlurMode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[24];
}
bool EGamescopeBlurMode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESLSHelper_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[25];
}
bool ESLSHelper_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EHDRVisualization_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[26];
}
bool EHDRVisualization_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EHDRToneMapOperator_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[27];
}
bool EHDRToneMapOperator_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ECPUGovernor_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[28];
}
bool ECPUGovernor_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EUpdaterType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[29];
}
bool EUpdaterType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EUpdaterState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[30];
}
bool EUpdaterState_IsValid(int value) {
  switch (value) {
    case 0:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EStorageBlockContentType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[31];
}
bool EStorageBlockContentType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EStorageBlockFileSystemType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[32];
}
bool EStorageBlockFileSystemType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EStorageDriveMediaType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[33];
}
bool EStorageDriveMediaType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESystemDisplayCompatibilityMode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[34];
}
bool ESystemDisplayCompatibilityMode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESteamOSCompatibilityCategory_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[35];
}
bool ESteamOSCompatibilityCategory_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESteamOSCompatibilityResultDisplayType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[36];
}
bool ESteamOSCompatibilityResultDisplayType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESteamDeckCompatibilityCategory_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[37];
}
bool ESteamDeckCompatibilityCategory_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESteamDeckCompatibilityResultDisplayType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[38];
}
bool ESteamDeckCompatibilityResultDisplayType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESteamDeckCompatibilityTestResult_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[39];
}
bool ESteamDeckCompatibilityTestResult_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EACState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[40];
}
bool EACState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EBatteryState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[41];
}
bool EBatteryState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EOSBranch_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[42];
}
bool EOSBranch_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EBrowserGPUStatus_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[43];
}
bool EBrowserGPUStatus_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EBrowserFeatureStatus_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[44];
}
bool EBrowserFeatureStatus_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGpuDriverId_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[45];
}
bool EGpuDriverId_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ECommunityItemClass_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[46];
}
bool ECommunityItemClass_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESteamDeckCompatibilityFeedback_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[47];
}
bool ESteamDeckCompatibilityFeedback_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EProvideDeckFeedbackPreference_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[48];
}
bool EProvideDeckFeedbackPreference_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EHardwareCompatibilityFeedbackDetails_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[49];
}
bool EHardwareCompatibilityFeedbackDetails_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 4:
    case 8:
    case 16:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGameFrameRateReportingPreference_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[50];
}
bool EGameFrameRateReportingPreference_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ETouchGesture_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[51];
}
bool ETouchGesture_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ESessionPersistence_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[52];
}
bool ESessionPersistence_IsValid(int value) {
  switch (value) {
    case -1:
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ENewSteamAnnouncementState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[53];
}
bool ENewSteamAnnouncementState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EForumType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[54];
}
bool EForumType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ECommentThreadType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[55];
}
bool ECommentThreadType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EBroadcastPermission_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[56];
}
bool EBroadcastPermission_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EBroadcastEncoderSetting_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[57];
}
bool EBroadcastEncoderSetting_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ECloudGamingPlatform_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[58];
}
bool ECloudGamingPlatform_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ECompromiseDetectionType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[59];
}
bool ECompromiseDetectionType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EAsyncGameSessionUserState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[60];
}
bool EAsyncGameSessionUserState_IsValid(int value) {
  switch (value) {
    case -1:
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EAsyncGameSessionUserVisibility_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[61];
}
bool EAsyncGameSessionUserVisibility_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGameRecordingType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[62];
}
bool EGameRecordingType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EGRMode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[63];
}
bool EGRMode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EExportCodec_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[64];
}
bool EExportCodec_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EProtoAppType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[65];
}
bool EProtoAppType_IsValid(int value) {
  switch (value) {
    case -2147483647 - 1:
    case 0:
    case 1:
    case 2:
    case 4:
    case 8:
    case 16:
    case 32:
    case 64:
    case 128:
    case 256:
    case 512:
    case 1024:
    case 2048:
    case 4096:
    case 8192:
    case 16384:
    case 32768:
    case 65536:
    case 1073741824:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EAppTestType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[66];
}
bool EAppTestType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EChildProcessQueryCommand_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[67];
}
bool EChildProcessQueryCommand_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EChildProcessQueryExitCode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[68];
}
bool EChildProcessQueryExitCode_IsValid(int value) {
  switch (value) {
    case -5:
    case -4:
    case -3:
    case -2:
    case -1:
    case 0:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EWindowsUpdateInstallationImpact_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[69];
}
bool EWindowsUpdateInstallationImpact_IsValid(int value) {
  switch (value) {
    case -1:
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EWindowsUpdateRebootBehavior_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[70];
}
bool EWindowsUpdateRebootBehavior_IsValid(int value) {
  switch (value) {
    case -1:
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EExternalSaleEventType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[71];
}
bool EExternalSaleEventType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EEnhancedMarketAppearanceStatus_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[72];
}
bool EEnhancedMarketAppearanceStatus_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EContentReportSubjectType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[73];
}
bool EContentReportSubjectType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EControlledLegalCategoryStatus_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[74];
}
bool EControlledLegalCategoryStatus_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EContentModeratorLevel_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[75];
}
bool EContentModeratorLevel_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 10:
    case 11:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EContentReportResolution_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[76];
}
bool EContentReportResolution_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EContentModerationSanction_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[77];
}
bool EContentModerationSanction_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EContentReportSubjectAction_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[78];
}
bool EContentReportSubjectAction_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EContentReportReason_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[79];
}
bool EContentReportReason_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
    case 27:
    case 28:
    case 29:
    case 30:
    case 31:
    case 32:
    case 33:
    case 34:
    case 35:
    case 36:
    case 37:
    case 38:
    case 39:
    case 40:
    case 41:
    case 42:
    case 43:
    case 44:
    case 45:
    case 46:
    case 47:
    case 48:
    case 49:
    case 50:
    case 51:
    case 52:
    case 53:
    case 54:
    case 55:
    case 56:
    case 57:
    case 58:
    case 59:
    case 60:
    case 61:
    case 62:
    case 63:
    case 64:
    case 65:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EResolutionAutomation_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[80];
}
bool EResolutionAutomation_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EPressOutletAction_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[81];
}
bool EPressOutletAction_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EPressOutletMemberPendingState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[82];
}
bool EPressOutletMemberPendingState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ECommentDeleteReason_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_enums_2eproto);
  return file_level_enum_descriptors_enums_2eproto[83];
}
bool ECommentDeleteReason_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
